#!/usr/bin/env python3
"""Refresh BackDrive's attributed snapshot of MIT's public AI Incident Tracker.

The page's actual embed identifies the dataset. The public API calls are taken
from the embed's shipped code. No private credentials or guessed endpoints are
used. Cache files are keyed to the source's lastUpdated timestamp, so a retry
can resume a partial download without mixing snapshots.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import tempfile
import time
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode, urlsplit
from urllib.request import Request, urlopen


TRACKER_PAGE = "https://airisk.mit.edu/ai-incident-tracker/incident-view"
CLASSIFICATION_NOTICE = (
    "MIT's published classifications are generated by Arcola AI's LLM pipeline "
    "from AI Incident Database reports. They are source classifications, not "
    "independent findings by BackDrive. Reporting is incomplete and selective; "
    "the labels, inferred harms and possible causes require review."
)
ROBOTICS_GOALS = {"Autonomous Driving", "Autonomous Drones", "Robotic Manipulation"}
ROBOTICS_WORDS = re.compile(
    r"\b(robot(?:s|ic|axi)?|driverless|self[- ]driving|autopilot|"
    r"autonomous (?:vehicle|car|taxi|bus|shuttle|truck|drone)s?)\b", re.I
)


def fetch(url: str) -> bytes:
    """Read a public response, with bounded retry and a modest request rate."""
    for attempt in range(5):
        try:
            request = Request(url, headers={"User-Agent": "BackDrive-public-data-import/1.0"})
            with urlopen(request, timeout=60) as response:
                return response.read()
        except (URLError, HTTPError, TimeoutError):
            if attempt == 4:
                raise
            time.sleep(2 ** attempt)
    raise RuntimeError("Unreachable retry state")


def json_fetch(url: str) -> dict[str, Any]:
    return json.loads(fetch(url))


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)


def discover() -> tuple[str, str, str, str]:
    page = fetch(TRACKER_PAGE).decode("utf-8")
    dataset_match = re.search(r'data-incident-dataset="([^"]+)"', page)
    embed_match = re.search(r'<script[^>]+src="(https://[^\"]+/embed\.js)"', page)
    if not dataset_match or not embed_match:
        raise ValueError("MIT page no longer declares the expected public embed; review the importer.")
    dataset, embed_url = dataset_match.group(1), embed_match.group(1)
    if dataset not in {"incidents", "incidents-arcola"}:
        raise ValueError(f"Unrecognized MIT dataset: {dataset}")
    embed = fetch(embed_url).decode("utf-8")
    for required in ["/data/incidents?", '"incident-list"', '"incident-detail"', '"incidentId"']:
        if required not in embed:
            raise ValueError("Public embed API changed; review the importer before refreshing.")
    url = urlsplit(embed_url)
    return dataset, f"{url.scheme}://{url.netloc}/api", embed_url, hashlib.sha256(embed.encode()).hexdigest()


def robotics_candidate(incident: dict[str, Any]) -> tuple[bool, str]:
    goals = [incident.get("aiGoalPrimary", ""), incident.get("aiGoalSecondary", "")]
    matching_goals = [goal for goal in goals if goal in ROBOTICS_GOALS]
    if matching_goals:
        return True, "Candidate selected from MIT AI purpose: " + ", ".join(matching_goals)
    match = ROBOTICS_WORDS.search(incident.get("title", ""))
    if match:
        return True, f"Candidate selected by title keyword: {match.group(0)}"
    return False, "No robotics candidate rule matched; this is not a finding that robotics is absent."


def to_case(incident: dict[str, Any], listed: dict[str, Any], updated: str) -> dict[str, Any]:
    number = str(incident["incidentId"])
    robotics, selection_basis = robotics_candidate(incident)
    source = f"https://incidentdatabase.ai/cite/{number}/"
    return {
        "id": f"AIID-{number}", "code": number, "title": incident.get("title") or listed["title"],
        "robotics": robotics, "roboticsCandidate": robotics, "roboticsBasis": selection_basis,
        "roboticsRelation": selection_basis + ". Relevance to a robotics application needs review.",
        "domain": incident.get("aiGoalPrimary") or "Unspecified application",
        "kind": "Reported incident", "recordType": "incident", "state": "Unassessed", "tone": "gray",
        "date": incident.get("date") or listed.get("date", ""),
        "summary": incident.get("summary") or incident.get("description", ""),
        "source": source, "sourceName": f"AI Incident Database, incident {number}",
        "sourceKey": "aiid", "sourceLabel": "AIID", "sourceRecordId": number,
        "importedFrom": "MIT AI Incident Tracker", "sourceUpdatedAt": updated,
        "capability": "Unassessed", "secondary": "", "capabilityBasis": "",
        "failure": "Not mapped", "test": "Unassessed", "testDetail": "", "testState": "Unassessed",
        "testSource": "", "relation": "", "hasResults": False, "connection": "",
        "missing": "Connections have not been reviewed.",
        "decision": "", "controlId": None, "evalIds": [], "nextTest": "",
        "sourceNotes": [],
        "tracker": {key: incident[key] for key in [
            "incidentId", "title", "date", "year", "domain", "subdomain", "entity", "intent", "timing", "confidence",
            "model", "modelName", "euAiActRiskClassification", "allegedDeployer", "allegedDeveloper", "allegedHarmedParties",
            "behaviourType", "aiGoalPrimary", "aiGoalSecondary", "aiGoalConfidence", "url", "reportCount", "classifiedAt",
            "promptVersion", "highestSeverityScore", "aiDevelopers", "aiModels", "aiModelNames", "aiModelVersions",
            "aiModelVariants", "aiIdentitySource",
        ] if key in incident},
        "trackerDetailUrl": "",
        "trackerList": listed,
    }


def write_detail_batches(cases: list[dict[str, Any]], details: dict[str, dict[str, Any]], output: Path) -> list[dict[str, Any]]:
    """Keep source objects complete, but avoid thousands of tiny published files."""
    batches = []
    for start in range(0, len(cases), 100):
        selected = cases[start:start + 100]
        filename = f"{start // 100 + 1:03}.json"
        url = f"imports/detail-batches/{filename}"
        records = {case["id"]: details[case["sourceRecordId"]] for case in selected}
        text = json.dumps({"records": records}, ensure_ascii=False, separators=(",", ":")) + "\n"
        atomic_write(output.parent / "detail-batches" / filename, text)
        data = text.encode("utf-8")
        batches.append({"url": url, "recordCount": len(records), "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()})
        for case in selected:
            case["trackerDetailUrl"] = url
    return batches


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "imports" / "tracker.js")
    parser.add_argument("--cache", type=Path, default=Path(tempfile.gettempdir()) / "backdrive-tracker-cache")
    parser.add_argument("--workers", type=int, default=4)
    args = parser.parse_args()
    if not 1 <= args.workers <= 8:
        parser.error("Use between one and eight workers.")
    dataset, api, embed_url, embed_hash = discover()
    list_url = api + "/data/incidents?" + urlencode({"src": dataset, "chartType": "incident-list"})
    listing = json_fetch(list_url)
    items = listing["items"]
    updated = listing["lastUpdated"]
    if len(items) != listing["totalIncidentsAll"] or len({str(i["incidentId"]) for i in items}) != len(items):
        raise ValueError("The source list is incomplete or has duplicate IDs; refusing a partial snapshot.")
    cache = args.cache / dataset / re.sub(r"[^0-9A-Za-z]", "-", updated)
    cache.mkdir(parents=True, exist_ok=True)
    atomic_write(cache / "listing.json", json.dumps(listing, ensure_ascii=False))

    def get_detail(item: dict[str, Any]) -> tuple[str, dict[str, Any]]:
        incident_id = str(item["incidentId"])
        filename = cache / f"{incident_id}.json"
        if filename.exists():
            incident = json.loads(filename.read_text())
        else:
            url = api + "/data/incidents?" + urlencode({"src": dataset, "chartType": "incident-detail", "incidentId": incident_id})
            response = json_fetch(url)
            if response.get("lastUpdated") != updated:
                raise ValueError("MIT updated during this import; run again to obtain a consistent snapshot.")
            incident = response["incident"]
            atomic_write(filename, json.dumps(incident, ensure_ascii=False))
            time.sleep(0.1)
        if str(incident.get("incidentId")) != incident_id or not incident.get("title"):
            raise ValueError(f"Missing or mismatched detail for incident {incident_id}")
        return incident_id, incident

    details: dict[str, dict[str, Any]] = {}
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = [pool.submit(get_detail, item) for item in items]
        for completed, future in enumerate(as_completed(futures), 1):
            key, incident = future.result()
            details[key] = incident
            if completed % 100 == 0 or completed == len(items):
                print(f"Retrieved {completed}/{len(items)} source details", flush=True)
    cases = [to_case(details[str(item["incidentId"])], item, updated) for item in items]
    cases.sort(key=lambda item: int(item["sourceRecordId"]))
    detail_batches = write_detail_batches(cases, details, args.output)
    local_aliases = {
        "CRUISE-2023": "AIID-726",
        "HWY18FH011": "AIID-321",
        "APPLE-2024": "AIID-861",
    }
    local_aliases = {key: value for key, value in local_aliases.items() if value in {i["id"] for i in cases}}
    metadata = {
        "sourceName": "MIT AI Incident Tracker", "sourceUrl": TRACKER_PAGE,
        "dataset": dataset, "apiBase": api, "listUrl": list_url, "embedUrl": embed_url,
        "embedSha256": embed_hash, "sourceUpdatedAt": updated,
        "importedAt": datetime.now(timezone.utc).isoformat(), "count": len(cases),
        "roboticsCandidateCount": sum(i["roboticsCandidate"] for i in cases),
        "classificationNotice": CLASSIFICATION_NOTICE,
        "harmFrameworkUrl": "https://airisk.mit.edu/ai-incident-tracker/harm-taxonomy",
        "harmSeverityScale": {"1": "Negligible", "2": "Minor", "3": "Substantial", "4": "Severe", "5": "Catastrophic"},
        "roboticsSelection": {
            "type": "Candidate retrieval, not incident-cause or capability classification",
            "aiPurposeMatches": sorted(ROBOTICS_GOALS), "titleRegex": ROBOTICS_WORDS.pattern,
            "notice": "Candidates need review. Existing hand-reviewed robotics examples may also be retained by the application.",
        },
        "localAliases": local_aliases,
        "detailFiles": "imports/detail-batches/{batch}.json",
        "detailBatches": detail_batches,
        "detailBatchCount": len(detail_batches),
        "detailRecordCount": len(cases),
        "licenses": [
            {"data": "MIT AI Risk Initiative data and published classifications", "license": "CC BY 4.0",
             "url": "https://creativecommons.org/licenses/by/4.0/", "termsUrl": TRACKER_PAGE,
             "attribution": "MIT AI Risk Initiative / MIT FutureTech; classifications produced by Arcola AI from AI Incident Database reports."},
            {"data": "Underlying AI Incident Database incident records", "license": "CC BY-SA 4.0",
             "url": "https://creativecommons.org/licenses/by-sa/4.0/", "termsUrl": "https://incidentdatabase.ai/terms-of-use/",
             "attribution": "Responsible AI Collaborative and AI Incident Database contributors. Individual incident pages credit submitters and editors."},
        ],
        "modifications": "Compact source fields retained in tracker and original list records in trackerList. Complete unchanged source incident objects retained by AIID ID in imports/detail-batches/*.json. Added stable application IDs, empty BackDrive mapping fields and disclosed robotics candidate retrieval. No original report article text, images or videos were copied.",
        "refreshCommand": "python3 backdrive/scripts/import_tracker.py",
        "filterOptions": {k: v for k, v in listing.items() if k not in {"items", "chartType", "totalIncidents", "totalIncidentsAll", "lastUpdated"}},
    }
    payload = {"metadata": metadata, "cases": cases}
    encoded = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    atomic_write(args.output, "// Source licenses and attribution: imports/ATTRIBUTION.md\nwindow.BACKDRIVE_TRACKER=" + encoded + ";\n")
    manifest = dict(metadata, outputSha256=hashlib.sha256(args.output.read_bytes()).hexdigest(), outputBytes=args.output.stat().st_size)
    atomic_write(args.output.with_name("tracker-manifest.json"), json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    print(f"Wrote {len(cases)} incidents ({metadata['roboticsCandidateCount']} robotics candidates) to {args.output}", flush=True)


if __name__ == "__main__":
    main()
