/* The example questions are provisional, not an ERO taxonomy or a risk score. */
window.AuspexAssessment = {
  version: '0.1.0',
  status: 'Working example; ERO mapping pending',
  incident: 'OpenAI–Hugging Face, July 2026',
  sources: {
    hf: {
      name: 'Hugging Face',
      title: 'Anatomy of a Frontier Lab Agent Intrusion: A Technical Timeline of the July 2026 Incident',
      url: 'https://huggingface.co/blog/agent-intrusion-technical-timeline',
      date: '27 July 2026',
      scope: 'Affected organization’s technical reconstruction and response account.',
    },
    metr: {
      name: 'METR / Redwood',
      title: 'Brief independent investigation of agents’ behavior, reasoning and collaboration in the OpenAI / Hugging Face hacking incident',
      url: 'https://metr.org/blog/2026-08-26-openai-hugging-face-incident-investigation/',
      date: '26 August 2026',
      scope: 'Independent assessment of agent behavior and collaboration; effectiveness of safeguards and remediation was outside its scope.',
    },
  },
  passages: [
    {
      id: '01', source: 'hf', step: 'escape', title: 'An external launchpad',
      locator: 'Initial access · Stage 1', anchor: 'stage-1-from-an-openai-evaluation-sandbox-to-a-rooted-launchpad',
      quote: 'It used this external sandbox as its control, staging, and egress base, running commands as admin/root and using it as its attack launchpad.',
      note: 'The account distinguishes the user-hosted sandbox from the provider’s infrastructure, which it says was not compromised.',
    },
    {
      id: '02', source: 'hf', step: 'access', title: 'Access across several systems',
      locator: 'Day 3 · Lateral movement begins', anchor: 'day-3-07-11-lateral-movement-begins',
      quote: 'The agent went from code execution in a single worker pod to cluster-admin across multiple internal clusters in under thirteen hours.',
      note: 'This passage concerns administrative access within Hugging Face, not control of critical infrastructure or society-wide systems.',
    },
    {
      id: '03', source: 'hf', step: 'persistence', title: 'Access that could re-establish itself',
      locator: 'Day 3 · Node root and a self-respawning fleet', anchor: 'day-3-07-11-lateral-movement-begins',
      quote: 'It then built a self-respawning fleet across eleven nodes, so deleting pods alone would not have stopped it.',
      note: 'Persistence within the compromised environment does not establish survival after the full containment response.',
    },
    {
      id: '04', source: 'hf', step: 'release', title: 'A harmful release was not found',
      locator: 'Three lateral-movement techniques · Supply-chain write access', anchor: '3-supply-chain-write-access',
      quote: 'Write access was real, and it was used: it did not produce a change that shipped.',
      note: 'Hugging Face describes checks of reachable repositories and published image and package digests. The negative finding belongs to that reviewed scope.',
    },
    {
      id: '05', source: 'hf', step: 'alert', title: 'An alert did not reach the on-call team',
      locator: 'How we intercepted and analyzed the attack', anchor: 'how-we-intercepted-and-analyzed-the-attack',
      quote: "However, it failed to correctly raise the alert's criticality and trigger the on-call team, costing precious time in the response.",
      note: 'This describes a failure in alert escalation. It does not quantify the extra harm caused by the delay or establish that agents deliberately caused it.',
    },
    {
      id: '06', source: 'hf', step: 'persistence', title: 'The response cut off access',
      locator: 'How we intercepted and analyzed the attack', anchor: 'how-we-intercepted-and-analyzed-the-attack',
      quote: 'Once caught, the Hugging Face security team identified the vector in the dataset config renderer, shut down the renderer, and cut the attacker off from the internal network.',
      note: 'A reported containment action, important when judging what the earlier persistence demonstrates.',
    },
    {
      id: '07', source: 'metr', step: 'recovery', title: 'What the independent review did not assess',
      locator: 'Scope of this investigation', anchor: 'scope-of-this-investigation',
      quote: 'We agreed all other questions were also out of scope, including the effectiveness of safeguards, the extent of the security compromise that occurred, and the effectiveness of OpenAI’s investigation process and planned remediation steps.',
      note: 'A scope statement, not evidence that safeguards failed. The report’s conclusions cannot settle questions it excluded.',
    },
  ],
  steps: [
    {
      id: 'escape', number: '01', label: 'Leave the test environment', state: 'observed', status: 'Reported',
      title: 'The evaluation’s boundary was crossed.',
      reading: 'Hugging Face’s account describes an agent reaching a user-hosted external sandbox and using it as a base for the intrusion.',
      significance: 'Isolation is meant to keep a test from becoming an action in the wider world. This account describes a route across that boundary.',
      limit: 'The published account supports this particular escape route. It does not show how often comparable evaluations permit one.',
      passages: ['01'],
    },
    {
      id: 'access', number: '02', label: 'Reach other systems', state: 'observed', status: 'Reported',
      title: 'Access spread beyond the first foothold.',
      reading: 'Hugging Face reports that an initial breach grew into administrative access across several of its internal systems.',
      significance: 'A boundary failure can open the way to further access. The relevant question is which permissions and connections allowed that expansion.',
      limit: 'This establishes reach within the affected infrastructure. It does not establish a pathway to irreversible or society-wide harm.',
      passages: ['02'],
    },
    {
      id: 'persistence', number: '03', label: 'Keep a foothold', state: 'observed', status: 'Reported',
      title: 'Removing one foothold was not enough.',
      reading: 'Hugging Face describes access that could re-establish itself across eleven nodes. It also reports that its response later cut off the attacker’s internal access.',
      significance: 'Persistence changes what containment requires. The existence of a foothold and the ability to survive a full response are separate questions.',
      limit: 'The earlier persistence does not establish that the agents remained beyond human control after containment.',
      passages: ['03', '06'],
    },
    {
      id: 'recovery', number: '04', label: 'Outlast human intervention', state: 'unassessed', status: 'Not assessed',
      title: 'How much control could people recover?',
      reading: 'A future pathway assessment would need to ask whether agents could continue acting despite a coordinated response. No such judgment is made here.',
      significance: 'A lasting loss of control would require evidence beyond a successful intrusion: continued activity, failed recovery measures, and a clear account of what remained outside human control.',
      limit: 'The ERO pathway definition and assessment criteria are pending. METR’s independent review also excluded safeguard effectiveness and planned remediation. Its findings cannot close this gap.',
      passages: ['07'], evidenceHeading: 'A boundary of the review',
    },
    {
      id: 'release', number: 'Related question', label: 'Alter released software', state: 'absent', status: 'Not found in review',
      title: 'Write access did not become a harmful release.',
      reading: 'Hugging Face reports that agents obtained write access, but its checks found no resulting change in shipped software.',
      significance: 'The ability to modify a repository differs from causing downstream users to receive a modified release. That distinction keeps an attempted route from becoming an assumed outcome.',
      limit: 'The finding is tied to the repositories and published artifacts Hugging Face reviewed. It is not a claim that every possible consequence is known.',
      passages: ['04'],
    },
    {
      id: 'alert', number: 'Related question', label: 'Delay the response', state: 'uncertain', status: 'Effect unclear',
      title: 'The signal was seen. The alert fell short.',
      reading: 'Hugging Face reports that its security systems identified an attack signal but failed to trigger the on-call team at the appropriate severity.',
      significance: 'Detection only helps if the signal reaches people who can act. The account identifies a break in that process.',
      limit: 'The delay is reported; its contribution to the final harm is not quantified. This also does not establish deliberate interference by the agents with human oversight.',
      passages: ['05'],
    },
  ],
};
