// Compact diagram labels. Full source-derived states remain in pathways.json.
window.AuspexLabels = {
  'X-01': ['Misaligned AI researcher', 'Warnings overridden', 'Successor capture', 'Institutional authority', 'Rival AI coordination', 'Autonomous industrial power', 'Human elimination'],
  'X-02': ['Consequential access', 'External execution base', 'Persistent operation', 'Automated productive assets', 'Defeated counteraction', 'Permanent loss of control'],
  'X-03': ['Influence-seeking systems', 'Control of essential services', 'Human dependence', 'A destabilizing crisis', 'Cascading failures', 'Recovery prevented'],
  'X-04': ['Measured outcomes', 'Proxy exploitation', 'Delegated correction', 'Correction captured', 'Competitive displacement', 'Loss of human control'],
  'X-05': ['Human work replaced', 'Bargaining power declines', 'Automated state dependence', 'Mutual reinforcement', 'Institutions cease to respond', 'No effective corrective channel'],
  'X-06': ['Autonomous firms', 'Closed production network', 'Human dependence', 'Failed intervention', 'Unrestrained resource use', 'Survival conditions erode', 'No surviving population'],
  'P-01': ['Accelerated procurement', 'Personal command loyalty', 'Orders against opponents', 'Countermand fails', 'Personal rule'],
  'P-02': ['Control of AI development', 'Hidden personal loyalties', 'Loyalties survive review', 'Military deployment', 'Lawful authority overridden', 'Government seized'],
  'P-03': ['Cyber-capability advantage', 'Vulnerable military systems', 'Military control compromised', 'Resistance defeated', 'Government seized'],
  'P-04': ['Exclusive industrial advantage', 'Reduced human dependence', 'Coercive force built', 'Intervention defeated', 'Private authority takes power'],
  'P-05': ['Privileged AI assistance', 'Political and surveillance advantage', 'Opposition weakened', 'Authority concentrated', 'Constitutional checks removed'],
  'P-06': ['A shared military adviser', 'Advice controlled by a faction', 'A fabricated consensus', 'Opposition fails to coordinate', 'The coup succeeds'],
  'W-01': ['AI-shaped intelligence', 'Threat exaggerated', 'Scrutiny fails', 'Nuclear use authorized', 'Nuclear casualties'],
  'W-02': ['Response authority delegated', 'Mistaken hostile action', 'Autonomous retaliation', 'Escalation outruns intervention', 'Destructive war'],
  'W-03': ['Shared military assets', 'Conventional strike', 'Deterrent perceived as threatened', 'Nuclear use authorized', 'Nuclear casualties'],
  'W-04': ['Counterforce capabilities', 'Retaliatory forces seem vulnerable', 'Waiting appears dangerous', 'Nuclear first use authorized', 'Nuclear casualties'],
  'W-05': ['Fear of AI monopoly', 'A closing intervention window', 'Preventive attack', 'National security threatened', 'Retaliation broadens the war'],
  'W-06': ['Responsibility concealed', 'Consequential cyber damage', 'Attack misattributed', 'Military retaliation', 'Broader war'],
  'W-07': ['AI-mediated negotiations', 'Difficult agreements accumulate', 'Diplomatic dependence', 'Cooperation deteriorates', 'Peaceful bargaining fails', 'Interstate war'],
  'W-08': ['Access to autonomous force', 'Fewer human constraints', 'Safeguards fail', 'Protection and intervention fail', 'Mass killing and displacement'],
  'B-01': ['Access to AI assistance', 'Relevant capability uplift', 'Practical constraints overcome', 'Exposure and transmission', 'Outbreak control fails', 'Mass mortality'],
  'B-02': ['Research outpaces oversight', 'Unsafe work permitted', 'Containment failure', 'Transmission beyond the facility', 'Outbreak control fails', 'Mass mortality'],
  'S-01': ['Shared grid-control models', 'Correlated control errors', 'Limits and reserves fail', 'Restoration and backup fail', 'Excess illness and deaths'],
  'S-02': ['AI-assisted cyber operations', 'Service-control access', 'Essential services disrupted', 'Recovery and substitutes fail', 'Severe civilian harm'],
  'S-03': ['Shared clinical AI', 'Systematic error', 'Error shapes care', 'Common cause goes undetected', 'Widespread avoidable harm'],
  'S-04': ['Shared financial models', 'Correlated responses to a shock', 'Financial feedback amplifies', 'Liquidity and buffers fail', 'Systemic credit contraction'],
  'S-05': ['Concentrated AI dependency', 'Shared service unavailable', 'Failover too slow', 'Obligations missed', 'Financial distress spreads'],
  'S-06': ['Agricultural automation', 'Crop-critical work disrupted', 'Production window missed', 'Food deficit goes uncovered', 'Famine'],
  'S-07': ['Short-term yield objectives', 'Ecological costs overlooked', 'Soil and ecosystem damage', 'Correction fails', 'Sustained regional damage'],
  'H-01': ['Arrest predictions affect hiring', 'Work and income lost', 'Recorded arrests increase', 'Predicted risk rises', 'Exclusion entrenched'],
  'H-02': ['Individual testing looks positive', 'Wide adoption', 'Shared withdrawal advice', 'Peer reinforcement', 'Education and employment lost'],
  'H-03': ['Message acceptance rewarded', 'Anxiety increases acceptance', 'Secrecy and fear encouraged', 'Communication norms change', 'Distrust and dependence'],
  'H-04': ['Planning advice delegated', 'AI pursues its preferred design', 'Public consent fabricated', 'Unwanted plan adopted'],
  'H-05': ['Automated driving with fallback', 'Ineffective braking response', 'Operator fails to intervene', 'Pedestrian killed'],
  'H-06': ['Unrestricted AI practice tool', 'Assisted performance improves', 'Independent practice may decline', 'Unaided performance worsens'],
};
