/* Conceptual adaptation of Bucknall & Dori-Hacohen (2022), §§2–6.
 * These are literature propositions, not an estimated causal model.
 */
window.AuspexFramework = {
  version: '0.2.0',
  paper: 'https://arxiv.org/html/2209.10604v1',
  title: 'Current and Near-Term AI as a Potential Existential Risk Factor',
  authors: 'Benjamin S. Bucknall & Shiri Dori-Hacohen',
  year: 2022,
  types: {
    structure: { label: 'Model connection', color: '#687f9b', description: 'A conceptual connection or contribution to wider risk; no probability is assigned.' },
    arms: { label: 'AI arms race', color: '#65d8e9', description: 'Competition can weaken safety incentives and divert resources from addressing risks.' },
    war: { label: 'Great-power war', color: '#f4a17c', description: 'Heightened geopolitical tensions could encourage the development or use of nuclear or biological weapons.' },
    misuse: { label: 'Deliberate misuse', color: '#ed809e', description: 'People may deliberately apply AI to harmful ends, including engineered pathogens or disinformation.' },
    emissions: { label: 'Carbon emissions', color: '#85cdb3', description: 'Developing and running AI systems can contribute to environmental risk through emissions.' },
    surveillance: { label: 'AI surveillance', color: '#c5b6fb', description: 'Surveillance can increase state control over citizens and help sustain repressive regimes.' },
    governance: { label: 'Lobbying & regulation', color: '#eab3d8', description: 'Changes in corporate influence can affect political decision-making and regulation.' },
    information: { label: 'Collective behavior', color: '#91b4ff', description: 'Changes in the information ecosystem can affect collective decisions and responses to shared threats.' },
  },
  nodes: [
    { id:'ai', code:'V01', label:'Current & near-term AI', kind:'origin', x:78, y:302, section:'S1', description:'The paper starts with AI systems that already exist or are under development. Its argument does not depend on assuming superintelligence.', limit:'A broad starting category, not a finding about any one model.' },
    { id:'cyber', code:'V02', label:'Cybersecurity', kind:'effect', x:285, y:65, section:'S4.SS2', description:'AI can change both cyber offense and defense: the ability to carry out attacks, monitor networks, and respond to intrusions.', limit:'The paper routes this effect through state–state relations. An organizational intrusion does not establish geopolitical escalation.', caseLink:true },
    { id:'states', code:'V03', label:'State–state relations', kind:'effect', x:285, y:185, section:'S3.SS1', description:'Competition over AI can alter relations between states, create arms-race incentives, and make international cooperation harder.', limit:'The OpenAI–Hugging Face evidence selected here does not establish an effect on relations between states.' },
    { id:'corporations', code:'V04', label:'State–corporation relations', kind:'effect', x:285, y:305, section:'S3.SS2', description:'The resources and influence of technology companies can change their relationship with governments and the public.', limit:'The presence of companies in an incident is not evidence of the power shift described in this proposition.' },
    { id:'citizens', code:'V05', label:'State–citizen relations', kind:'effect', x:285, y:425, section:'S3.SS3', description:'AI-enabled surveillance can increase the power of states over individuals, particularly where oversight and legal protections are weak.', limit:'No surveillance or state–citizen mapping has been assessed for the selected incident.' },
    { id:'information', code:'V06', label:'Information ecosystem', kind:'effect', x:285, y:545, section:'S4.SS1', description:'Social media and recommender systems can shape information access, polarization, and the capacity for collective decisions.', limit:'Agent-to-agent communication in this incident is not automatically evidence of an effect on the public information ecosystem.' },
    { id:'resources', code:'V07', label:'Diverted resources', kind:'factor', x:535, y:150, section:'S5.SS1', description:'Competition and immediate crises can draw attention and resources away from preventing or responding to existential threats.', limit:'A general risk factor: it may weaken a response without being a catastrophe in itself.' },
    { id:'decisions', code:'V08', label:'Compromised decisions', kind:'factor', x:535, y:445, section:'S5.SS1', description:'Political division, misinformation, or concentrated influence can weaken institutions’ ability to make and carry out collective decisions.', limit:'The short label abbreviates the paper’s “compromised political decision-making”; it is not a judgment about individual decisions in the incident.' },
    { id:'unaligned', code:'V09', label:'Unaligned AGI', kind:'risk', x:785, y:50, section:'S5.SS6', description:'Present-day development and competitive pressures can influence the safety of later, more capable AI systems.', limit:'The paper describes a possible future risk. It does not establish that the incident involved AGI.' },
    { id:'natural', code:'V10', label:'Natural risks', kind:'risk', x:785, y:155, section:'S5.SS5', description:'Natural hazards may become harder to manage if institutions have fewer resources or less capacity to coordinate.', limit:'Included in the literature model. There is no selected incident assessment for this category.' },
    { id:'nuclear', code:'V11', label:'Nuclear risk', kind:'risk', x:785, y:260, section:'S5.SS2', description:'Heightened rivalry and changes in cybersecurity may affect strategic stability and the possibility of nuclear conflict.', limit:'A proposed mechanism in the literature, not a consequence established by this intrusion.' },
    { id:'biological', code:'V12', label:'Biological risk', kind:'risk', x:785, y:365, section:'S5.SS3', description:'The paper discusses engineered pathogens, international rivalry, and the role of public trust in responding to pandemics.', limit:'These are different mechanisms. A link to this category does not mean all of them apply.' },
    { id:'environmental', code:'V13', label:'Environmental risk', kind:'risk', x:785, y:470, section:'S5.SS4', description:'AI can affect emissions as well as the shared information and political action needed to address environmental threats.', limit:'No environmental consequence is assessed from the selected incident passages.' },
    { id:'regime', code:'V14', label:'Stable repressive regime', kind:'risk', x:785, y:575, section:'S3.SS3', description:'Persistent, technology-supported repression is included under the paper’s broader definition of existential catastrophe.', limit:'Existential risk here includes permanent loss of humanity’s potential, not only extinction.' },
    { id:'existential', code:'V15', label:'Existential catastrophe', kind:'outcome', x:1035, y:302, section:'S2', description:'The paper uses Ord’s definition: a threat to humanity’s long-term potential, including extinction, unrecoverable collapse, or permanent dystopia.', limit:'No incident-to-catastrophe inference, probability, or completed chain is asserted in this atlas.' },
  ],
  edges: [
    ['ai','cyber','structure','S4.SS2'],
    ['ai','states','structure','S3.SS1'],
    ['ai','corporations','structure','S3.SS2'],
    ['ai','citizens','structure','S3.SS3'],
    ['ai','information','structure','S4.SS1'],
    ['ai','information','misuse','S6'],
    ['ai','biological','misuse','S5.SS3'],
    ['ai','environmental','emissions','S5.SS4'],
    ['cyber','states','structure','S6'],
    ['states','unaligned','arms','S6'],
    ['states','resources','arms','S6'],
    ['states','nuclear','war','S6'],
    ['states','biological','war','S6'],
    ['corporations','decisions','governance','S6'],
    ['citizens','regime','surveillance','S6'],
    ['information','decisions','information','S6'],
    ['information','biological','information','S6'],
    ['information','environmental','information','S6'],
    ['resources','existential','structure','S5.SS1'],
    ['decisions','existential','structure','S5.SS1'],
    ['unaligned','existential','structure','S2'],
    ['natural','existential','structure','S2'],
    ['nuclear','existential','structure','S2'],
    ['biological','existential','structure','S2'],
    ['environmental','existential','structure','S2'],
    ['regime','existential','structure','S2'],
  ].map(([from,to,type,section], index) => ({ id:`E${String(index+1).padStart(2,'0')}`, from,to,type,section, status:'Literature proposition' })),
  edgeReadings: {
    E01:'AI can improve attack methods as well as detection and response, changing the conditions under which cyber operations take place.',
    E02:'Competition over AI development can change relations between states and encourage an arms-race dynamic.',
    E03:'AI-related wealth and influence can alter the balance of power between technology companies and governments.',
    E04:'AI surveillance can increase a state’s knowledge of, and power over, people within its reach.',
    E05:'Search and recommendation systems can shape public information even without a deliberately malicious operator.',
    E06:'People can also use AI deliberately to target disinformation and sow confusion in public discourse.',
    E07:'The paper proposes that malicious actors could use advances in AI to help develop dangerous pathogens.',
    E08:'Training and operating AI systems can contribute emissions that add to environmental pressures.',
    E09:'Changes in cyber offense and defense can affect states’ relative capabilities and relations. This is the paper’s route from cybersecurity into the wider model.',
    E10:'An AI arms race could encourage developers to cut safety precautions, with consequences for later, more capable systems.',
    E11:'Competition over AI could divert attention and resources from preventing or responding to other existential threats.',
    E12:'Heightened rivalry could become military conflict and increase the possibility of a nuclear first strike.',
    E13:'Heightened international rivalry could encourage the development or use of biological weapons.',
    E14:'Corporate influence, lobbying, and disputes over regulation can affect political decision-making and responses to shared risks.',
    E15:'AI-enabled surveillance could help establish and sustain a repressive regime.',
    E16:'Polarization and misinformation can make collective political decisions harder to reach and implement.',
    E17:'Misinformation and damaged public trust can weaken coordinated responses to a pandemic.',
    E18:'Misinformation can obstruct agreement and collective action on environmental threats.',
    E19:'Resources diverted from prevention and response can increase vulnerability across several sources of risk. This adapted connection represents a general factor, not a single hazard.',
    E20:'Weakened political decision-making can impair responses to several sources of risk. This adapted connection represents a general factor, not a single hazard.',
    E21:'The paper includes unaligned advanced AI among the possible sources of permanent loss of humanity’s potential.',
    E22:'The paper includes extreme natural hazards among the possible sources of existential catastrophe.',
    E23:'Large-scale nuclear conflict could produce nuclear winter, reduced agricultural output, and widespread famine.',
    E24:'A sufficiently severe pandemic is considered a possible source of existential catastrophe.',
    E25:'The environmental category concerns severe outcomes that could threaten humanity’s long-term potential.',
    E26:'A permanent repressive dystopia counts under the paper’s definition of existential catastrophe, even without human extinction.',
  },
  routes: [
    { id:'all', label:'All pathways', caption:'Select a concept or line to inspect its argument.', nodes:[] },
    { id:'cyber', label:'Cyber & strategic stability', caption:'Cyber capability → relations between states → possible wider harm.', nodes:['ai','cyber','states','resources','unaligned','nuclear','biological','existential'] },
    { id:'information', label:'Information & collective action', caption:'Information systems → collective decisions → the ability to respond.', nodes:['ai','information','decisions','biological','environmental','existential'] },
    { id:'power', label:'Power & governance', caption:'Relations between states, companies, and citizens.', nodes:['ai','states','corporations','citizens','resources','decisions','regime','unaligned','existential'] },
    { id:'direct', label:'Direct contributions', caption:'Deliberate misuse and emissions, as discussed in the paper.', nodes:['ai','biological','environmental','existential'] },
  ],
  criteria: {
    escape: { code:'C01', state:'S', question:'Did activity reach an external execution environment?', concept:'Safe exploration', conceptKey:'exploration', criterion:'The source describes execution in an environment outside the original evaluation boundary.', barrier:'Evaluation isolation', barrierState:'Crossed in the reported route' },
    access: { code:'C02', state:'S', question:'Did access expand to other protected systems?', concept:'Avoiding negative consequences', conceptKey:'consequences', criterion:'The source describes administrative access to more than the initially compromised workload.', barrier:'Permissions & segmentation', barrierState:'Failed in the reported scope' },
    persistence: { code:'C03', state:'S', question:'Could the foothold re-establish itself?', concept:'Corrigibility', conceptKey:'corrigibility', criterion:'The source describes a mechanism that recreates access after a component is removed.', barrier:'Containment & revocation', barrierState:'Access later cut off; full effectiveness unassessed' },
    release: { code:'C04', state:'N', question:'Did an unauthorized change reach released software?', concept:'Avoiding negative consequences', conceptKey:'consequences', criterion:'A reviewed repository change is tied to a shipped artifact or release.', barrier:'Execution & release controls', barrierState:'No shipped change found in the stated review' },
    alert: { code:'C05', state:'U', question:'How much did delayed alerting change the outcome?', concept:'Scalable oversight', conceptKey:'oversight', criterion:'A supported account connects alert delay to additional activity or loss.', barrier:'Detection → human response', barrierState:'Escalation failed; added harm unclear' },
    recovery: { code:'C06', state:'⊥', question:'Could agents act beyond a coordinated human response?', concept:'Corrigibility', conceptKey:'corrigibility', criterion:'Evidence establishes continued activity after specified recovery measures, with scope and observation limits.', barrier:'Human recovery of control', barrierState:'Not assessed' },
  },
  research: [
    { id:'R01', year:'2022', type:'Risk model', title:'Current and Near-Term AI as a Potential Existential Risk Factor', author:'Benjamin S. Bucknall & Shiri Dori-Hacohen', url:'https://arxiv.org/html/2209.10604v1', locator:'§§2–6 · Figure 1 · Table 1', use:'The atlas adapts the paper’s effects, general risk factors, risk sources, and seven named mechanisms. Labels and layout are redrawn; general factors connect to the overall outcome. This is a conceptual adaptation, not an exact facsimile of Figure 1.', relation:'Published at AIES 2022. Bucknall conducted the work during a research internship at ERO.', license:'CC BY 4.0' },
    { id:'R02', year:'2021', type:'Safety concepts', title:'Important Safety Considerations for Current AI Research', author:'Ben Bucknall · Existential Risk Observatory', url:'https://www.existentialriskobservatory.org/artificial-intelligence/important-safety-considerations-for-current-ai-research/', locator:'Reward hacking · Scalable oversight · Safe exploration · Transparency · Corrigibility', use:'Provides named safety questions for reading the incident. The operational criteria C01–C06 are X-oscope proposals, not a rubric published by ERO.', relation:'ERO’s public explainer, drawing on Concrete Problems in AI Safety.' },
    { id:'R03', year:'2025', type:'Evidence & governance', title:'International Agreements on AI Safety', author:'Rebecca Scholefield, Samuel Martin & Otto Barten', url:'https://arxiv.org/html/2503.18956v1#S1.SS2.SSS4', locator:'§1.2.4 · Arguments', use:'Discusses safety cases as structured arguments supported by evidence. Informs the separation of claims, reasons, and sources; it does not validate this incident assessment.', relation:'Scholefield and Barten are affiliated with ERO.', license:'CC BY 4.0' },
    { id:'R04', year:'Reference', type:'Risk definitions', title:'What is an existential risk?', author:'Existential Risk Observatory', url:'https://www.existentialriskobservatory.org/risks/', locator:'What is an Existential Risk? · Risk Factors', use:'Distinguishes an existential catastrophe from conditions that may increase its likelihood or weaken the ability to respond.', relation:'ERO’s public risk overview.' },
  ],
};
