// Schematic labels and source-linked reading positions, not a quantitative model.
window.AuspexInspection = {
  incidents: {
    'HF-2026': { labels: ['External launchpad', 'Internal persistence', 'Renderer shutdown'], kind: 'network' },
    'OB-2019': { labels: ['Spending as a proxy', 'Unequal care allocation', 'A revised prediction target'], kind: 'comparison' },
    'KL-2025': { labels: ['Work moves to AI', 'Hiring resumes'] },
    'AN-2025': { labels: ['AI-assisted intrusion', 'Accounts banned'] },
    'SUP-2026': { labels: ['Military-supplier data stolen'] },
    'SUR-2026': { labels: ['AI-assisted surveillance', 'Refusal overcome'] },
    'BIO-2026': { labels: ['Relay access', 'Bans and takedowns', 'Access restored'] },
    'SP-2025': { labels: ['Airbase strikes', 'Dual-use aircraft damaged', 'No public posture change'] },
    'AI-2026': { labels: ['Malicious contribution', 'Maintainer rejects it'] },
    'PYPI-2026': { labels: ['Malicious package published', 'Scanner credentials leaked', 'Package removed'] },
    'SCOPE-2026': { labels: ['Third-party intrusion', 'Remote-control script', 'Agent stops the attack'] },
    'OP47-2026': { labels: ['Wrong company reached', 'User records changed', 'Backend stops responding'] },
    'OP46-2026': { labels: ['Unintended internet access', 'Administrator access', 'Run budget exhausted'] },
    'MALI-2026': { labels: ['National surveillance platform', 'Warrant check removed', 'Local deployment continues'] },
    'UY-2026': { labels: ['Vulnerability profiles', 'Assistance and refusals', 'Accounts banned'] },
    'CAR-2026': { labels: ['Covert political broadcasts', 'Refusal and reframing', 'Investigation and account bans'] },
    'DRONE-2026': { labels: ['Military-drone development', 'No human engagement approval', 'Accounts banned'] },
    'FLU-2026': { labels: ['High-risk research request', 'Stronger models restricted', 'Weaker-model assistance'] },
    'PAP-2026': { labels: ['AI-assisted campaign', 'Hundreds of compromises', 'Local blocking and containment'] },
    'NT-2018': {
      labels: ['Human fallback', 'Operator distraction', 'Fatal collision'],
      observations: [
        { text: 'A safety operator was responsible for monitoring the road and intervening when needed.', evidence: ['NT-summary'] },
        { text: 'The distracted operator did not intervene in time to prevent the collision.', evidence: ['NT-summary'] },
        { text: 'The pedestrian was struck and killed. NTSB identified operator distraction, organizational factors and system-design contributors.', evidence: ['NT-summary'] },
      ],
    },
    'ED-2023': {
      labels: ['AI-assisted practice', 'Unaided examination', 'Teacher-informed tutor'],
      observations: [
        { text: 'Students practised mathematics with GPT-based assistance in a field experiment at one Turkish high school.', evidence: ['ED-outcome'] },
        { text: 'Unrestricted assistance was followed by lower performance on an exam without AI access.', evidence: ['ED-outcome'] },
        { text: 'The teacher-informed GPT Tutor package largely avoided that harm. Unaided-exam improvement over the control group was not established.', evidence: ['ED-outcome'] },
      ],
    },
  },
  barriers: {
    'renderer-shutdown': { input: 'Internal access', control: 'Renderer shutdown', result: 'Access cut off', dependency: 'Dependence on the renderer', failureRoute: 'Independent execution route', observation: 2 },
    'alert-escalation': { input: 'Attack signal', control: 'Severity classification', result: 'On-call team not reached', dependency: 'Correct alert severity', failureRoute: 'Criticality classified too low', failureObserved: true },
    'prediction-target': { input: 'Spending proxy', control: 'Revise the target', result: 'Measured bias reduced', dependency: 'Prediction tracks medical need', failureRoute: 'Another proxy for treatment access', observation: 2 },
    'management-reversal': { input: 'Cost-cutting deployment', control: 'Management reverses course', result: 'Hiring resumes', dependency: 'Authority to change deployment', observation: 1 },
    'account-enforcement': { input: 'AI-assisted intrusions', control: 'Ban accounts', result: 'Reported disruption', observation: 1 },
    'model-refusal': { input: 'Prohibited request', control: 'Initial refusal', result: 'Further prompting succeeds', dependency: 'Resistance to further prompting', failureRoute: 'Request rephrased', failureObserved: true, observation: 1 },
    'relay-enforcement': { input: 'Relay access', control: 'Bans and takedowns', result: 'Access restored within days', dependency: 'Exclusion across access routes', failureRoute: 'Fresh identities and intermediaries', failureObserved: true, observation: 1 },
    'maintainer-review': { input: 'Malicious contribution', control: 'Maintainer review', result: 'Contribution rejected', dependency: 'Human vigilance', failureRoute: 'Malicious change approved', observation: 1 },
    'human-fallback': { input: 'Need to intervene', control: 'Safety operator', result: 'Fatal collision', failureRoute: 'Operator distraction', failureObserved: true, observation: 1 },
    'tutor-package': { input: 'Mathematics practice', control: 'Teacher-informed tutor', result: 'Measured harm largely avoided', observation: 2 },
    'pypi-removal': { input: 'Published malware', control: 'Registry removal', result: 'Package removed', dependency: 'Exposure before removal', failureRoute: 'Leaked credentials remain usable', observation: 2 },
    'scope-recognition': { input: 'Unauthorized intrusion', control: 'Scope recognition', result: 'Attack stopped', dependency: 'Repeatable decision to stop', failureRoute: 'Attack continues in resampling', failureObserved: true, failureLabel: 'Observed in local replay', failureResult: 'Attack continued', observation: 2 },
    'run-budget': { input: 'Administrator access', control: 'Run budget', result: 'Session ended', dependency: 'Finite execution budget', inputObservation: 1, observation: 2 },
    'warrant-check': { input: 'Surveillance dossiers', control: 'Warrant requirement', result: 'Check removed', dependency: 'Independent legal control', failureRoute: 'Operator removes the check', failureObserved: true, observation: 1, resultObservation: 1 },
    'local-deployment': { input: 'AI-assisted engineering', control: 'Ban account', result: 'Local platform unaffected', dependency: 'Product uses local models', failureRoute: 'Independent local operation', failureObserved: true, observation: 2 },
    'uyghur-refusal': { input: 'Coercive requests', control: 'Selected refusals', result: 'Other assistance supplied', dependency: 'Coverage of the whole operation', failureRoute: 'Other assistance remains available', observation: 1, resultObservation: 1 },
    'car-refusal': { input: 'Fabricated accusations', control: 'Refuse request', result: 'Operator reframes request', dependency: 'Recognition across requests', failureRoute: 'Political objective reframed', failureObserved: true, observation: 1, resultObservation: 1 },
    'drone-enforcement': { input: 'Weapons development', control: 'Ban accounts', result: 'Access restricted', dependency: 'Dependence on provider access', observation: 2 },
    'bio-classifier': { input: 'High-risk research', control: 'Biological classifiers', result: 'Weaker models used', dependency: 'Lower model capability', failureRoute: 'Capable unguarded models', observation: 1 },
    'papercut-waf': { input: 'Intrusion attempt', control: 'Web firewall', result: 'One attempt blocked', dependency: 'Coverage of the attack route', observation: 2 },
  },
};
